# Sprint Boot configuration
# 
# Need Tomcat to consume the X-Forwarded-* headers from AWS ALB
server:
  forward-headers-strategy: NATIVE
  tomcat:
    redirect-context-root: false
    remoteip:
      host-header: Host
      internal-proxies: ".+"
      port-header: X-Fowarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
